### Exploratory Data Analysis: Healthcare Patient Data

In [46]:
# import libraries
import pandas as pd
import numpy as np
import psycopg2
from sqlalchemy import create_engine
from dotenv import load_dotenv
import os

import matplotlib.pyplot as plt
import plotly.express as px

# setting to show all columns of data frames
pd.set_option('display.max_columns', None)

In [3]:
# load .env; loads credentials into memeory 
load_dotenv(override=True)

True

In [4]:
host=os.getenv('DB_HOST')
user=os.getenv('DB_USER')
password=os.getenv('DB_PASSWORD')
database=os.getenv('DB_NAME')
port=os.getenv('DB_PORT')

In [5]:
# select data from admission_source table
connection_string = f"postgresql+psycopg2://{user}:{password}@{host}:{port}/{database}"
try:
    engine = create_engine(connection_string)

    with engine.connect() as conn:
        admission_source_df = pd.read_sql('''SELECT * FROM admission_source;''', con = conn)

        conn.close()

except (Exception) as error:
        error_log   = 'Error writing data to table: admission_source. Check system file.'                  
        with open('error_log.txt','w') as error:
           error.write(error_log)


admission_source_df.head()

   admission_source_id                    admission_source_description
0                    1                              Physician Referral
1                    2                                 Clinic Referral
2                    3                                    HMO Referral
3                    4                        Transfer from a hospital
4                    5  Transfer from a Skilled Nursing Facility (SNF)

In [6]:
admission_source_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 2 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   admission_source_id           26 non-null     int64
 1   admission_source_description  26 non-null     str
dtypes: int64(1), str(1)
memory usage: 548.0 bytes

In [7]:
# select data from admission_type table
connection_string = f"postgresql+psycopg2://{user}:{password}@{host}:{port}/{database}"
try:
    engine = create_engine(connection_string)

    with engine.connect() as conn:
        admission_type_df = pd.read_sql('''SELECT * FROM admission_type;''', con = conn)

        conn.close()

except (Exception) as error:
        error_log   = 'Error selecting data from admission_type table. Check system file.'                  
        with open('error_log.txt','w') as error:
           error.write(error_log)


admission_type_df.head()

   admission_type_id admission_type_description
0                  1                  Emergency
1                  2                     Urgent
2                  3                   Elective
3                  4                    Newborn
4                  5              Not Available

In [10]:
admission_type_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   admission_type_id           8 non-null      int64
 1   admission_type_description  8 non-null      str
dtypes: int64(1), str(1)
memory usage: 260.0 bytes

In [8]:
# select data from discharge_disposition table
connection_string = f"postgresql+psycopg2://{user}:{password}@{host}:{port}/{database}"
try:
    engine = create_engine(connection_string)

    with engine.connect() as conn:
        discharge_disposition_df = pd.read_sql('''SELECT * FROM discharge_disposition;''', con = conn)

        conn.close()

except (Exception) as error:
        error_log   = 'Error selecting data from discharge_disposition table. Check system file.'                  
        with open('error_log.txt','w') as error:
           error.write(error_log)


discharge_disposition_df.head()

   discharge_disposition_id                  discharge_disposition_description
0                         1                                 Discharged to home
1                         2  Discharged/transferred to another short term h...
2                         3                      Discharged/transferred to SNF
3                         4                      Discharged/transferred to ICF
4                         5  Discharged/transferred to another type of inpa...

In [12]:
discharge_disposition_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   discharge_disposition_id           30 non-null     int64
 1   discharge_disposition_description  30 non-null     str
dtypes: int64(1), str(1)
memory usage: 612.0 bytes

In [9]:
# select data from icd9 table
connection_string = f"postgresql+psycopg2://{user}:{password}@{host}:{port}/{database}"
try:
    engine = create_engine(connection_string)

    with engine.connect() as conn:
        icd9_df = pd.read_sql('''SELECT * FROM icd9;''', con = conn)

        conn.close()

except (Exception) as error:
        error_log   = 'Error selecting data from icd9 table. Check system file.'                  
        with open('error_log.txt','w') as error:
           error.write(error_log)


icd9_df.head()

,id,code_start_str,code_end_str,code_start_int,code_end_int,icd9_description
0,1,NaN,NaN,1.0,139.0,INFECTIOUS AND PARASITIC DISEASES (001-139)
1,2,NaN,NaN,140.0,239.0,NEOPLASMS (140-239)
2,3,NaN,NaN,240.0,279.0,"ENDOCRINE, NUTRITIONAL AND METABOLIC DISEASES,..."
3,4,NaN,NaN,280.0,289.0,DISEASES OF THE BLOOD AND BLOOD-FORMING ORGANS...
4,5,NaN,NaN,290.0,319.0,"MENTAL, BEHAVIORAL AND NEURODEVELOPMENTAL DISO..."

In [14]:
icd9_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                19 non-null     int64
 1   code_start_str    2 non-null      str
 2   code_end_str      2 non-null      str
 3   code_start_int    17 non-null     float64
 4   code_end_int      17 non-null     float64
 5   icd9_description  19 non-null     str
dtypes: float64(2), int64(1), str(3)
memory usage: 1.0 KB

In [10]:
# select data from patient table
connection_string = f"postgresql+psycopg2://{user}:{password}@{host}:{port}/{database}"
try:
    engine = create_engine(connection_string)

    with engine.connect() as conn:
        patient = pd.read_sql('''SELECT * FROM patient;''', con = conn)

        conn.close()

except (Exception) as error:
        error_log   = 'Error selecting data from patient table. Check system file.'                  
        with open('error_log.txt','w') as error:
           error.write(error_log)


patient.head()

   patient_nbr              race  gender    age        weight
0          135         Caucasian  Female  50-60  Not Captured
1          378         Caucasian  Female  50-60  Not Captured
2          729         Caucasian  Female  80-90  Not Captured
3          774         Caucasian  Female  80-90  Not Captured
4          927  African American  Female  30-40  Not Captured

In [16]:
patient.info()

<class 'pandas.DataFrame'>
RangeIndex: 71518 entries, 0 to 71517
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   patient_nbr  71518 non-null  int64
 1   race         71518 non-null  str
 2   gender       71518 non-null  str
 3   age          71518 non-null  str
 4   weight       71518 non-null  str
dtypes: int64(1), str(4)
memory usage: 2.7 MB

In [11]:
patient_race = patient.groupby(['race', 'gender'])['patient_nbr'].count().reset_index()
patient_race

                race           gender  patient_nbr
0   African American           Female         7841
1   African American             Male         5063
2              Asian           Female          251
3              Asian             Male          255
4          Caucasian           Female        27569
5          Caucasian             Male        25950
6           Hispanic           Female          810
7           Hispanic             Male          702
8       Not Captured           Female          960
9       Not Captured             Male          943
10      Not Captured  Unknown/Invalid            2
11             Other           Female          594
12             Other             Male          577
13             Other  Unknown/Invalid            1

In [12]:
# select records from the patient_encouonter table
connection_string = f"postgresql+psycopg2://{user}:{password}@{host}:{port}/{database}"
try:
    engine = create_engine(connection_string)

    with engine.connect() as conn:
        patient_encounter = pd.read_sql('''SELECT patient_nbr,encounter_id
                                            ,admission_type_id
                                            ,admission_source_id
                                            ,discharge_disposition_id
                                            ,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures
                                            ,num_medications,number_outpatient,number_emergency,number_inpatient
                                            ,pe.diag_1,icd9_1.icd9_description AS diag_1_desc
                                            ,pe.diag_2,icd9_2.icd9_description AS diag_2_desc
                                            ,pe.diag_3,icd9_3.icd9_description AS diag_3_desc
                                            ,number_diagnoses
                                            ,max_glu_serum,"a1cresult",metformin,repaglinide,nateglinide,chlorpropamide,acetohexamide
                                            ,glimepiride,glipizide,glyburide,tolbutamide,tolazamide,examide,pioglitazone,rosiglitazone
                                            ,troglitazone,acarbose,miglitol,citoglipton,insulin,"glyburidemetformin","glipizidemetformin"
                                            ,"glimepiridepioglitazone","metforminrosiglitazone","metforminpioglitazone"
                                            ,change_in_meds,"diabetesmed",readmitted
                                            FROM patient_encounter pe
                                            INNER JOIN icd9 icd9_1
                                                ON TO_NUMBER(pe.diag_1, 'L999.99') BETWEEN icd9_1.code_start_int AND icd9_1.code_end_int
                                                    OR pe.diag_1 BETWEEN icd9_1.code_start_str AND icd9_1.code_end_str
                                            INNER JOIN icd9 AS icd9_2
                                                ON TO_NUMBER(pe.diag_2, 'L999.99') BETWEEN icd9_2.code_start_int AND icd9_2.code_end_int
                                                    OR pe.diag_2 BETWEEN icd9_2.code_start_str AND icd9_2.code_end_str
                                            INNER JOIN icd9 AS icd9_3
                                                ON TO_NUMBER(pe.diag_3, 'L999.99') BETWEEN icd9_3.code_start_int AND icd9_3.code_end_int
                                                    OR pe.diag_3 BETWEEN icd9_3.code_start_str AND icd9_3.code_end_str
                                        ;''', con = conn)

        conn.close()

except (Exception) as error:
        error_log   = 'Error select data from patient_encounter table. Check system file.'                  
        with open('error_log.txt','w') as error:
           error.write(error_log)


patient_encounter.head()

,patient_nbr,encounter_id,admission_type_id,admission_source_id,discharge_disposition_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_1_desc,diag_2,diag_2_desc,diag_3,diag_3_desc,number_diagnoses,max_glu_serum,a1cresult,metformin,repaglinide,nateglinide,chlorpropamide,acetohexamide,glimepiride,glipizide,glyburide,tolbutamide,tolazamide,examide,pioglitazone,rosiglitazone,troglitazone,acarbose,miglitol,citoglipton,insulin,glyburidemetformin,glipizidemetformin,glimepiridepioglitazone,metforminrosiglitazone,metforminpioglitazone,change_in_meds,diabetesmed,readmitted
0,8222157,2278392,6,1,25,1,Not Captured,Pediatrics-Endocrinology,41,0,1,0,0,0,250.83,"ENDOCRINE, NUTRITIONAL AND METABOLIC DISEASES,...",799,"SYMPTOMS, SIGNS, AND ILL-DEFINED CONDITIONS (7...",799,"SYMPTOMS, SIGNS, AND ILL-DEFINED CONDITIONS (7...",1,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No Change,No,No
1,55629189,149190,1,7,1,3,Not Captured,Not Captured,59,0,18,0,0,0,276,"ENDOCRINE, NUTRITIONAL AND METABOLIC DISEASES,...",250.01,"ENDOCRINE, NUTRITIONAL AND METABOLIC DISEASES,...",255,"ENDOCRINE, NUTRITIONAL AND METABOLIC DISEASES,...",9,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Change,Yes,>30
2,86047875,64410,1,7,1,2,Not Captured,Not Captured,11,5,13,2,0,1,648,"COMPLICATIONS OF PREGNANCY, CHILDBIRTH, AND TH...",250,"ENDOCRINE, NUTRITIONAL AND METABOLIC DISEASES,...",V27,INFECTIOUS AND PARASITIC DISEASES (001-139),6,None,None,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No Change,Yes,No
3,86047875,64410,1,7,1,2,Not Captured,Not Captured,11,5,13,2,0,1,648,"COMPLICATIONS OF PREGNANCY, CHILDBIRTH, AND TH...",250,"ENDOCRINE, NUTRITIONAL AND METABOLIC DISEASES,...",V27,SUPPLEMENTARY CLASSIFICATION OF FACTORS INFLUE...,6,None,None,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No Change,Yes,No
4,82442376,500364,1,7,1,2,Not Captured,Not Captured,44,1,16,0,0,0,8,INFECTIOUS AND PARASITIC DISEASES (001-139),250.43,"ENDOCRINE, NUTRITIONAL AND METABOLIC DISEASES,...",403,DISEASES OF THE CIRCULATORY SYSTEM (390-459),7,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Change,Yes,No

In [19]:
patient_encounter.info()

<class 'pandas.DataFrame'>
RangeIndex: 111861 entries, 0 to 111860
Data columns (total 49 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   patient_nbr               111861 non-null  int64
 1   encounter_id              111861 non-null  int64
 2   admission_type_id         111861 non-null  int64
 3   admission_source_id       111861 non-null  int64
 4   discharge_disposition_id  111861 non-null  int64
 5   time_in_hospital          111861 non-null  int64
 6   payer_code                111861 non-null  str
 7   medical_specialty         111861 non-null  str
 8   num_lab_procedures        111861 non-null  int64
 9   num_procedures            111861 non-null  int64
 10  num_medications           111861 non-null  int64
 11  number_outpatient         111861 non-null  int64
 12  number_emergency          111861 non-null  int64
 13  number_inpatient          111861 non-null  int64
 14  diag_1                    111861 non-null  str
 15  diag_1_desc               111861 non-null  str
 16  diag_2                    111861 non-null  str
 17  diag_2_desc               111861 non-null  str
 18  diag_3                    111861 non-null  str
 19  diag_3_desc               111861 non-null  str
 20  number_diagnoses          111861 non-null  int64
 21  max_glu_serum             111861 non-null  str
 22  a1cresult                 111861 non-null  str
 23  metformin                 111861 non-null  str
 24  repaglinide               111861 non-null  str
 25  nateglinide               111861 non-null  str
 26  chlorpropamide            111861 non-null  str
 27  acetohexamide             111861 non-null  str
 28  glimepiride               111861 non-null  str
 29  glipizide                 111861 non-null  str
 30  glyburide                 111861 non-null  str
 31  tolbutamide               111861 non-null  str
 32  tolazamide                111861 non-null  str
 33  examide                   111861 non-null  str
 34  pioglitazone              111861 non-null  str
 35  rosiglitazone             111861 non-null  str
 36  troglitazone              111861 non-null  str
 37  acarbose                  111861 non-null  str
 38  miglitol                  111861 non-null  str
 39  citoglipton               111861 non-null  str
 40  insulin                   111861 non-null  str
 41  glyburidemetformin        111861 non-null  str
 42  glipizidemetformin        111861 non-null  str
 43  glimepiridepioglitazone   111861 non-null  str
 44  metforminrosiglitazone    111861 non-null  str
 45  metforminpioglitazone     111861 non-null  str
 46  change_in_meds            111861 non-null  str
 47  diabetesmed               111861 non-null  str
 48  readmitted                111861 non-null  str
dtypes: int64(13), str(36)
memory usage: 41.8 MB

In [13]:
# merge admission_source and patient_encounter
patient_encounter_df = pd.merge(patient_encounter, admission_source_df, on='admission_source_id', how='inner')

In [14]:
# merge admission_type and patient_encounter
patient_encounter_df = pd.merge(patient_encounter_df, admission_type_df, on='admission_type_id', how='inner')

In [15]:
# merge discharge_disposition_df and patient_encounter
patient_encounter_df = pd.merge(patient_encounter_df, discharge_disposition_df, on='discharge_disposition_id', how='inner')

In [23]:
# patient_encounter_df.head(3)
patient_encounter_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 111861 entries, 0 to 111860
Data columns (total 52 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   patient_nbr                        111861 non-null  int64
 1   encounter_id                       111861 non-null  int64
 2   admission_type_id                  111861 non-null  int64
 3   admission_source_id                111861 non-null  int64
 4   discharge_disposition_id           111861 non-null  int64
 5   time_in_hospital                   111861 non-null  int64
 6   payer_code                         111861 non-null  str
 7   medical_specialty                  111861 non-null  str
 8   num_lab_procedures                 111861 non-null  int64
 9   num_procedures                     111861 non-null  int64
 10  num_medications                    111861 non-null  int64
 11  number_outpatient                  111861 non-null  int64
 12  number_emergency                   111861 non-null  int64
 13  number_inpatient                   111861 non-null  int64
 14  diag_1                             111861 non-null  str
 15  diag_1_desc                        111861 non-null  str
 16  diag_2                             111861 non-null  str
 17  diag_2_desc                        111861 non-null  str
 18  diag_3                             111861 non-null  str
 19  diag_3_desc                        111861 non-null  str
 20  number_diagnoses                   111861 non-null  int64
 21  max_glu_serum                      111861 non-null  str
 22  a1cresult                          111861 non-null  str
 23  metformin                          111861 non-null  str
 24  repaglinide                        111861 non-null  str
 25  nateglinide                        111861 non-null  str
 26  chlorpropamide                     111861 non-null  str
 27  acetohexamide                      111861 non-null  str
 28  glimepiride                        111861 non-null  str
 29  glipizide                          111861 non-null  str
 30  glyburide                          111861 non-null  str
 31  tolbutamide                        111861 non-null  str
 32  tolazamide                         111861 non-null  str
 33  examide                            111861 non-null  str
 34  pioglitazone                       111861 non-null  str
 35  rosiglitazone                      111861 non-null  str
 36  troglitazone                       111861 non-null  str
 37  acarbose                           111861 non-null  str
 38  miglitol                           111861 non-null  str
 39  citoglipton                        111861 non-null  str
 40  insulin                            111861 non-null  str
 41  glyburidemetformin                 111861 non-null  str
 42  glipizidemetformin                 111861 non-null  str
 43  glimepiridepioglitazone            111861 non-null  str
 44  metforminrosiglitazone             111861 non-null  str
 45  metforminpioglitazone              111861 non-null  str
 46  change_in_meds                     111861 non-null  str
 47  diabetesmed                        111861 non-null  str
 48  readmitted                         111861 non-null  str
 49  admission_source_description       111861 non-null  str
 50  admission_type_description         111861 non-null  str
 51  discharge_disposition_description  111861 non-null  str
dtypes: int64(13), str(39)
memory usage: 44.4 MB

In [16]:
# merge patient and patient_encounter
patient_all_df = pd.merge(patient, patient_encounter_df, on='patient_nbr', how='inner')

In [25]:
# veiw all merged patient info
patient_all_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 111861 entries, 0 to 111860
Data columns (total 56 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   patient_nbr                        111861 non-null  int64
 1   race                               111861 non-null  str
 2   gender                             111861 non-null  str
 3   age                                111861 non-null  str
 4   weight                             111861 non-null  str
 5   encounter_id                       111861 non-null  int64
 6   admission_type_id                  111861 non-null  int64
 7   admission_source_id                111861 non-null  int64
 8   discharge_disposition_id           111861 non-null  int64
 9   time_in_hospital                   111861 non-null  int64
 10  payer_code                         111861 non-null  str
 11  medical_specialty                  111861 non-null  str
 12  num_lab_procedures                 111861 non-null  int64
 13  num_procedures                     111861 non-null  int64
 14  num_medications                    111861 non-null  int64
 15  number_outpatient                  111861 non-null  int64
 16  number_emergency                   111861 non-null  int64
 17  number_inpatient                   111861 non-null  int64
 18  diag_1                             111861 non-null  str
 19  diag_1_desc                        111861 non-null  str
 20  diag_2                             111861 non-null  str
 21  diag_2_desc                        111861 non-null  str
 22  diag_3                             111861 non-null  str
 23  diag_3_desc                        111861 non-null  str
 24  number_diagnoses                   111861 non-null  int64
 25  max_glu_serum                      111861 non-null  str
 26  a1cresult                          111861 non-null  str
 27  metformin                          111861 non-null  str
 28  repaglinide                        111861 non-null  str
 29  nateglinide                        111861 non-null  str
 30  chlorpropamide                     111861 non-null  str
 31  acetohexamide                      111861 non-null  str
 32  glimepiride                        111861 non-null  str
 33  glipizide                          111861 non-null  str
 34  glyburide                          111861 non-null  str
 35  tolbutamide                        111861 non-null  str
 36  tolazamide                         111861 non-null  str
 37  examide                            111861 non-null  str
 38  pioglitazone                       111861 non-null  str
 39  rosiglitazone                      111861 non-null  str
 40  troglitazone                       111861 non-null  str
 41  acarbose                           111861 non-null  str
 42  miglitol                           111861 non-null  str
 43  citoglipton                        111861 non-null  str
 44  insulin                            111861 non-null  str
 45  glyburidemetformin                 111861 non-null  str
 46  glipizidemetformin                 111861 non-null  str
 47  glimepiridepioglitazone            111861 non-null  str
 48  metforminrosiglitazone             111861 non-null  str
 49  metforminpioglitazone              111861 non-null  str
 50  change_in_meds                     111861 non-null  str
 51  diabetesmed                        111861 non-null  str
 52  readmitted                         111861 non-null  str
 53  admission_source_description       111861 non-null  str
 54  admission_type_description         111861 non-null  str
 55  discharge_disposition_description  111861 non-null  str
dtypes: int64(13), str(43)
memory usage: 47.8 MB

In [17]:
# change datatype 
patient_all_df['race'] = patient_all_df['race'].astype('category')
patient_all_df['gender'] = patient_all_df['gender'].astype('category')

In [18]:
# descriptive statistics on numeric data only
patient_all_df.describe(include=[np.number])

,patient_nbr,encounter_id,admission_type_id,admission_source_id,discharge_disposition_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses
count,1.118610e+05,1.118610e+05,111861.000000,111861.000000,111861.000000,111861.000000,111861.000000,111861.000000,111861.000000,111861.000000,111861.000000,111861.000000,111861.000000
mean,5.451339e+07,1.655728e+08,2.044135,5.673085,3.733687,4.416883,42.580488,1.320094,15.914975,0.369566,0.195743,0.647294,7.406201
std,3.869589e+07,1.026138e+08,1.440597,4.066566,5.284085,3.023391,19.637076,1.684047,8.035091,1.255761,0.917712,1.275084,1.931722
min,1.350000e+02,1.252200e+04,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
25%,2.344706e+07,8.545324e+07,1.000000,1.000000,1.000000,2.000000,31.000000,0.000000,10.000000,0.000000,0.000000,0.000000,6.000000
50%,4.563692e+07,1.526633e+08,1.000000,7.000000,1.000000,4.000000,44.000000,1.000000,15.000000,0.000000,0.000000,0.000000,8.000000
75%,8.754908e+07,2.302967e+08,3.000000,7.000000,4.000000,6.000000,56.000000,2.000000,20.000000,0.000000,0.000000,1.000000,9.000000
max,1.895026e+08,4.438672e+08,8.000000,25.000000,28.000000,14.000000,132.000000,6.000000,81.000000,42.000000,76.000000,21.000000,16.000000

In [19]:
# descriptive statistics on subset (specific numeric columns) ; 'admission_type_id', 
patient_all_df[['admission_source_id', 'discharge_disposition_id','num_lab_procedures'
                ,'num_procedures','num_medications', 'number_outpatient', 'number_emergency'
                ,'number_inpatient','number_diagnoses']].describe()

,admission_source_id,discharge_disposition_id,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses
count,111861.000000,111861.000000,111861.000000,111861.000000,111861.000000,111861.000000,111861.000000,111861.000000,111861.000000
mean,5.673085,3.733687,42.580488,1.320094,15.914975,0.369566,0.195743,0.647294,7.406201
std,4.066566,5.284085,19.637076,1.684047,8.035091,1.255761,0.917712,1.275084,1.931722
min,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
25%,1.000000,1.000000,31.000000,0.000000,10.000000,0.000000,0.000000,0.000000,6.000000
50%,7.000000,1.000000,44.000000,1.000000,15.000000,0.000000,0.000000,0.000000,8.000000
75%,7.000000,4.000000,56.000000,2.000000,20.000000,0.000000,0.000000,1.000000,9.000000
max,25.000000,28.000000,132.000000,6.000000,81.000000,42.000000,76.000000,21.000000,16.000000

In [20]:
fig = px.box(patient_all_df[['admission_source_id', 'discharge_disposition_id','num_lab_procedures'
                ,'num_procedures','num_medications', 'number_outpatient', 'number_emergency'
                ,'number_inpatient','number_diagnoses']].describe().loc[['mean', 'max', 'min','std', '50%']]
                , title='Descriptive Statistics: All Patient Data')

fig.update_xaxes(showgrid=False)
fig.update_yaxes(showgrid=False)

fig.show()

In [21]:
# perform analysis

# patient per admission types (Why) : represents the priority and nature of the patient's arrival, often used for scheduling and administrative analysis.
patient_admission_type = patient_all_df.groupby('admission_type_description')['patient_nbr'].count().sort_values(ascending=False).reset_index()
patient_admission_type

  admission_type_description  patient_nbr
0                  Emergency        58044
1                   Elective        22102
2                     Urgent        20374
3               Not Selected         5777
4              Not Available         5180
5                 Not Mapped          347
6              Trauma Center           25
7                    Newborn           12

In [ ]:
# top 3 admission types
df_3 = patient_admission_type.head(3)
fig = px.bar(df_3, x = 'admission_type_description'
             ,y='patient_nbr', title='Admission Types Distribution'
             , color='admission_type_description'
             , labels={'patient_nbr': 'patients', 'admission_type_description': 'descriptions'})
fig.update_layout(showlegend=False)
fig.update_xaxes(showgrid=False)
fig.update_yaxes(showgrid=False)
fig.show()

In [23]:
# patient per admission source : (Where) - identifies the location or context of the patient immediately prior to being admitted to the facility
patient_admission_source = patient_all_df.groupby('admission_source_description').agg({
    'patient_nbr': 'count',
    'time_in_hospital': 'mean',
    }).sort_values('patient_nbr', ascending=False)
patient_admission_source = patient_admission_source.reset_index()
patient_admission_source

,admission_source_description,patient_nbr,time_in_hospital
0,Emergency Room,61728,4.334921
1,Physician Referral,33366,4.341935
2,Not Selected,7275,4.149416
3,Transfer from a hospital,4227,6.226638
4,Transfer from another health care facility,2476,4.401454
5,Clinic Referral,1265,4.669565
6,Transfer from a Skilled Nursing Facility (SNF),945,5.876190
7,HMO Referral,200,4.930000
8,Not Mapped,175,4.491429
9,Not Available,135,3.400000
10,Transfer from hospital inpt/same fac reslt in ...,35,10.371429
11,Court/Law Enforcement,17,5.411765
12,Transfer from critial access hospital,8,4.375000
13,Extramural Birth,3,3.000000
14,Normal Delivery,2,2.500000
15,Transfer from Ambulatory Surgery Center,2,6.000000
16,Sick Baby,2,3.000000

In [27]:
# visualize top 5
fig = px.bar(patient_admission_source.head(), x='admission_source_description'
             , y='patient_nbr', color='time_in_hospital'
             , barmode='group'
             , title='Admission Source Distribution')

fig.update_xaxes(showgrid=False)
fig.update_yaxes(showgrid=False)

fig.show()

In [26]:
# visualize the top 5
df_5 = patient_admission_source.head()
fig = px.pie(df_5, values='patient_nbr', names='admission_source_description'
             ,  title='Admission Sources Distribution')
fig.show()

In [32]:
# Top Ten Primary Diagnosis Codes
connection_string = f"postgresql+psycopg2://{user}:{password}@{host}:{port}/{database}"
try:
    engine = create_engine(connection_string)

    with engine.connect() as conn:
        primary_top_ten_df = pd.read_sql('''WITH patient_primary_diagnosis_cte AS (
                                            SELECT pe.patient_nbr
                                                ,diag_1
                                                ,icd9_1.icd9_description
                                            FROM patient_encounter pe
                                            INNER JOIN icd9 icd9_1
                                                ON TO_NUMBER(pe.diag_1, 'L999.99') BETWEEN icd9_1.code_start_int AND 
                                                        icd9_1.code_end_int
                                                    OR pe.diag_1 BETWEEN icd9_1.code_start_str AND 
                                                        icd9_1.code_end_str
                                            )
                                            SELECT diag_1 AS primary_diagnosis
                                                , icd9_description AS description
                                                , COUNT(ppdc.patient_nbr) AS num_of_patients
                                            FROM patient_primary_diagnosis_cte ppdc
                                            GROUP BY diag_1
                                                ,icd9_description
                                            ORDER BY COUNT(ppdc.patient_nbr) DESC 
                                            LIMIT 10;
                                        ''', con = conn)

        conn.close()

except (Exception) as error:
        error_log   = 'Error select data from patient_encounter table. Check system file.'                  
        with open('error_log.txt','w') as error:
           error.write(error_log)


primary_top_ten_df.head(10)

,primary_diagnosis,description,num_of_patients
0,428,DISEASES OF THE CIRCULATORY SYSTEM (390-459),6862
1,414,DISEASES OF THE CIRCULATORY SYSTEM (390-459),6581
2,786,"SYMPTOMS, SIGNS, AND ILL-DEFINED CONDITIONS (7...",4016
3,410,DISEASES OF THE CIRCULATORY SYSTEM (390-459),3614
4,486,DISEASES OF THE RESPIRATORY SYSTEM (460-519),3508
5,427,DISEASES OF THE CIRCULATORY SYSTEM (390-459),2766
6,491,DISEASES OF THE RESPIRATORY SYSTEM (460-519),2275
7,715,DISEASES OF THE MUSCULOSKELETAL SYSTEM AND CON...,2151
8,682,DISEASES OF THE SKIN AND SUBCUTANEOUS TISSUE (...,2042
9,434,DISEASES OF THE CIRCULATORY SYSTEM (390-459),2028

In [33]:
# visualize
fig = px.bar(primary_top_ten_df, x='primary_diagnosis',
             y='num_of_patients', color='num_of_patients'
             , title='Top Ten Primary Diagnosis Codes'
             , hover_data='description')

fig.show()

In [34]:
# patient per discharge disposition types : the final destination or setting a patient goes to upon leaving a healthcare facility,
# determining their next level of care.  It defines whether the patient is going home (with or without support), 
# transferring to another facility (like nursing or rehab), or leaving against medical advice
patient_discharge_disposition_type = patient_all_df.groupby('discharge_disposition_description').agg({
    'patient_nbr': 'count'
}).sort_values(by='patient_nbr', ascending=False)
patient_discharge_disposition_type = patient_discharge_disposition_type.reset_index()
patient_discharge_disposition_type['total_patients'] = patient_discharge_disposition_type['patient_nbr'].sum()
patient_discharge_disposition_type['pct_discharge_disposition'] = ((patient_discharge_disposition_type['patient_nbr'] / patient_discharge_disposition_type['patient_nbr'].sum()) * 100).round(1)
patient_discharge_disposition_type

,discharge_disposition_description,patient_nbr,total_patients,pct_discharge_disposition
0,Discharged to home,65882,111861,58.9
1,Discharged/transferred to SNF,15165,111861,13.6
2,Discharged/transferred to home with home healt...,14755,111861,13.2
3,Not Selected,4129,111861,3.7
4,Discharged/transferred to another short term h...,2384,111861,2.1
5,Discharged/transferred to another rehab fac in...,2246,111861,2.0
6,Expired,1684,111861,1.5
7,Discharged/transferred to another type of inpa...,1275,111861,1.1
8,Not Mapped,1067,111861,1.0
9,Discharged/transferred to ICF,886,111861,0.8
10,Left AMA,686,111861,0.6
11,Discharged/transferred to a long term care hos...,424,111861,0.4
12,Hospice / home,418,111861,0.4
13,Hospice / medical facility,387,111861,0.3
14,Discharged/transferred to a federal health car...,156,111861,0.1
15,Discharged/transferred to home under care of H...,118,111861,0.1
16,Discharged/transferred within this institution...,73,111861,0.1
17,Discharged/transferred to a nursing facility c...,51,111861,0.0
18,Admitted as an inpatient to this hospital,24,111861,0.0
19,Discharged/transferred/referred to this instit...,14,111861,0.0
20,Discharged/transferred/referred another instit...,11,111861,0.0
21,"Expired at home. Medicaid only, hospice.",8,111861,0.0
22,Neonate discharged to another hospital for neo...,7,111861,0.0
23,Discharged/transferred to another Type of Heal...,6,111861,0.0
24,Still patient or expected to return for outpat...,3,111861,0.0
25,"Expired in a medical facility. Medicaid only, ...",2,111861,0.0

In [35]:
# visualize discharge_disposition_description : Top Three
fig = px.bar(patient_discharge_disposition_type.head(3), x='discharge_disposition_description'
             ,y='patient_nbr', hover_data='pct_discharge_disposition', color='discharge_disposition_description'
            ,title='Discharge Disposition Distribution')

fig.update_layout(showlegend=False)
fig.update_xaxes(showgrid=False)
fig.update_yaxes(showgrid=False)

fig.show()

In [36]:
# Distribution of Race and Gender
race_gender_df = patient_all_df.groupby(['race', 'gender'])['patient_nbr'].count().reset_index()
race_gender_df

                race           gender  patient_nbr
0   African American           Female        12691
1   African American             Male         8127
2              Asian           Female          342
3              Asian             Male          356
4          Caucasian           Female        43903
5          Caucasian             Male        40170
6           Hispanic           Female         1159
7           Hispanic             Male         1041
8       Not Captured           Female         1202
9       Not Captured             Male         1207
10      Not Captured  Unknown/Invalid            3
11             Other           Female          856
12             Other             Male          803
13             Other  Unknown/Invalid            1

In [38]:
# Top Eight
top_seven = race_gender_df.head(8)
top_seven

               race  gender  patient_nbr
0  African American  Female        12691
1  African American    Male         8127
2             Asian  Female          342
3             Asian    Male          356
4         Caucasian  Female        43903
5         Caucasian    Male        40170
6          Hispanic  Female         1159
7          Hispanic    Male         1041

In [39]:
#visualize
fig = px.bar(top_seven, x='gender', y='patient_nbr', color='race'
             , title='Distribution of Race vs Gender')
fig.update_xaxes(showgrid=False)
fig.update_yaxes(showgrid=False)
fig.show()

In [40]:
# Determine the number of readmitted patients and the percentage of total encounters that they represent
readmitted_df = patient_all_df.groupby('readmitted').agg({
    'encounter_id': 'count',
    'patient_nbr': 'nunique'
    }) #.sort_values(by='encounter_id', ascending=False)
readmitted_df = readmitted_df.reset_index()
readmitted_df['total_encounters'] = readmitted_df['encounter_id'].sum()
readmitted_df['percent_encounters'] = ((readmitted_df['encounter_id'] / readmitted_df['total_encounters']) * 100).round(1)
readmitted_df

  readmitted  encounter_id  patient_nbr  total_encounters  percent_encounters
0        <30         12496         8834            111861                11.2
1        >30         39016        24139            111861                34.9
2         No         60349        54820            111861                53.9

In [41]:
# visualize
fig = px.bar(readmitted_df, x='readmitted', y='encounter_id', color='encounter_id'
             , title='Readmittance Encounters'
             , hover_data='percent_encounters')
fig.update_xaxes(showgrid=False)
fig.update_yaxes(showgrid=False)
fig.show()

In [ ]:
# Identify the age distribution of patients
age_df = patient_all_df.groupby(['age', 'readmitted'])['patient_nbr'].count().reset_index()
age_df

       age readmitted  patient_nbr
0     0-10        <30            4
1     0-10        >30           28
2     0-10         No          144
3    10-20        <30           46
4    10-20        >30          243
5    10-20         No          503
6    20-30        <30          270
7    20-30        >30          550
8    20-30         No         1027
9    30-40        <30          479
10   30-40        >30         1251
11   30-40         No         2383
12   40-50        <30         1072
13   40-50        >30         3403
14   40-50         No         5934
15   50-60        <30         1830
16   50-60        >30         6309
17   50-60         No        10610
18   60-70        <30         2724
19   60-70        >30         8587
20   60-70         No        13297
21   70-80        <30         3382
22   70-80        >30        10340
23   70-80         No        14957
24   80-90        <30         2325
25   80-90        >30         7218
26   80-90         No         9698
27  90-100        <30          364
28  90-100        >30         1087
29  90-100         No         1796

In [43]:
# visualize
fig = px.bar(age_df, x='age', y='patient_nbr', color='readmitted', barmode='group'
             , title='Age vs Readmittance')

fig.update_xaxes(showgrid=False)
fig.update_yaxes(showgrid=False)

fig.show()

In [44]:
# 11. Calculate the average number of medications prescribed for patients in each age group and a change in meds per age group
# age_meds_prescribed_and_changed_df = patient_all_df.groupby(['age', 'change_in_meds'])['patient_nbr'].count().reset_index()
age_meds_prescribed_and_changed_df = patient_all_df.groupby(['age', 'change_in_meds']).agg({
    'patient_nbr': 'count',
    'num_medications': 'mean'
    }).reset_index()
age_meds_prescribed_and_changed_df

       age change_in_meds  patient_nbr  num_medications
0     0-10         Change           40         7.250000
1     0-10      No Change          136         5.867647
2    10-20         Change          323         8.910217
3    10-20      No Change          469         7.449893
4    20-30         Change          971        12.681771
5    20-30      No Change          876        10.583333
6    30-40         Change         1945        15.468380
7    30-40      No Change         2168        12.812269
8    40-50         Change         5018        17.194500
9    40-50      No Change         5391        13.546837
10   50-60         Change         8937        18.613741
11   50-60      No Change         9812        14.507644
12   60-70         Change        11975        19.201754
13   60-70      No Change        12633        14.984485
14   70-80         Change        13051        18.458279
15   70-80      No Change        15628        14.523356
16   80-90         Change         8185        17.443616
17   80-90      No Change        11056        13.644989
18  90-100         Change         1251        15.992806
19  90-100      No Change         1996        12.320641

In [45]:
# visualize
fig = px.bar(age_meds_prescribed_and_changed_df, x='age', y='patient_nbr', color='change_in_meds', barmode='group'
             , title='Distribution of Medication Changes / Avg Number of Medications Over Age'
             , hover_data='num_medications')

fig.update_xaxes(showgrid=False)
fig.update_yaxes(showgrid=False)

fig.show()